import type { ColorNameCategories } from "./colorDefinitions";

export const colorDefinitionsLight: ColorNameCategories = {
  success: {
    text: "green-600",
    textEmphasis: "green-700",
    textPlaceholder: "green-300",
    fill: "green-600",
    fillEmphasis: "green-700",
    bg: "green-600",
    bgEmphasis: "green-700",
    bgHover: "green-700",
    shadow: "green-900",
    border: "green-900",
    scrollbarThumb: "green-900",
    scrollbarTrack: "green-600",
    scrollbarCorner: "green-600",
    accent: "green-600",
  },
  error: {
    text: "red-800",
    textEmphasis: "red-900",
    textPlaceholder: "red-300",
    fill: "red-800",
    fillEmphasis: "red-900",
    bg: "red-600",
    bgEmphasis: "red-700",
    bgHover: "red-700",
    shadow: "red-900",
    border: "red-900",
    scrollbarThumb: "red-900",
    scrollbarTrack: "red-600",
    scrollbarCorner: "red-600",
    accent: "red-600",
  },
  interactive: {
    text: "sky-700",
    textEmphasis: "sky-800",
    textPlaceholder: "sky-300",
    fill: "sky-700",
    fillEmphasis: "sky-800",
    bg: "sky-700",
    bgEmphasis: "sky-800",
    bgHover: "sky-800",
    shadow: "sky-950",
    border: "sky-600",
    scrollbarThumb: "sky-600",
    scrollbarTrack: "sky-300",
    scrollbarCorner: "sky-300",
    accent: "sky-600",
  },
  primary: {
    text: "stone-600", //leftsidebar(header/footer) text
    textEmphasis: "stone-700",
    textPlaceholder: "stone-300",
    fill: "stone-600", //leftsidebar(header/footer) icon
    fillEmphasis: "stone-700", //leftsidebar(header/footer) icon
    bg: "stone-100",
    bgEmphasis: "stone-200",
    bgHover: "stone-200",
    shadow: "stone-600", //leftsidebar/Nav(Body/Buttons) shadow
    border: "stone-300", //breadcrumb border,
    scrollbarThumb: "stone-300",
    scrollbarTrack: "stone-100",
    scrollbarCorner: "stone-100",
    accent: "stone-600",
  },
  secondary: {
    text: "stone-700", //leftsidebar(header/footer) text
    textEmphasis: "stone-900",
    textPlaceholder: "stone-300",
    fill: "stone-700", //leftsidebar(header/footer) icon
    fillEmphasis: "stone-900", //leftsidebar(header/footer) icon
    bg: "stone-300",
    bgEmphasis: "stone-200",
    bgHover: "stone-200",
    shadow: "stone-800", //leftsidebar/Nav(Body/Buttons) shadow
    border: "stone-400", //breadcrumb border
    scrollbarThumb: "stone-400",
    scrollbarTrack: "stone-300",
    scrollbarCorner: "stone-300",
    accent: "stone-700",
  },
  white: {
    text: "stone-50",
    textEmphasis: "stone-50",
    textPlaceholder: "stone-700",
    fill: "stone-50",
    fillEmphasis: "stone-50",
    bg: "stone-50",
    bgEmphasis: "stone-50",
    bgHover: "stone-50",
    shadow: "stone-50",
    border: "stone-50",
    scrollbarThumb: "stone-50",
    scrollbarTrack: "stone-50",
    scrollbarCorner: "stone-50",
    accent: "stone-50",
  },
};
