import type { ColorDefinitionCategories } from "./colorDefinitions";
import { colorDefinitionsLight } from "./colorDefinitionsLight";

export const colorDefinitionsDark: ColorDefinitionCategories = {
  success: {
    text: "text-green-400",
    textOpacity: "text-green-400/50",
    textHover: "hover:text-green-300",
    textEmphasis: "text-green-300",
    fill: "fill-green-400",
    fillOpacity: "fill-green-400/50",
    fillEmphasis: "fill-green-300",
    fillHover: "hover:fill-green-300",
    bg: "bg-green-500",
    bgOpacity: "bg-green-500/50",
    bgEmphasis: "bg-green-700",
    bgHover: "hover:bg-green-700",
    shadow: "shadow-green-50",
    border: "border-green-600",
    scrollbarThumb: "scrollbar-thumb-green-600",
    scrollbarTrack: "scrollbar-track-green-400",
    scrollbarCorner: "scrollbar-corner-green-400",
  },
  error: {
    text: "text-red-400",
    textOpacity: "text-red-400/50",
    textHover: "hover:text-red-300",
    textEmphasis: "text-red-300",
    fill: "fill-red-400",
    fillOpacity: "fill-red-400/50",
    fillEmphasis: "fill-red-300",
    fillHover: "hover:fill-red-300",
    bg: "bg-red-500", //BaseToggle.syncTarget
    bgOpacity: "bg-red-500/50", //BaseToggle.syncTarget
    bgEmphasis: "bg-red-700",
    bgHover: "hover:bg-red-700",
    shadow: "shadow-red-50",
    border: "border-red-600",
    scrollbarThumb: "scrollbar-thumb-red-600",
    scrollbarTrack: "scrollbar-track-red-400",
    scrollbarCorner: "scrollbar-corner-red-400",
  },
  interactive: {
    text: "text-blue-500",
    textOpacity: "text-blue-500/50",
    textHover: "hover:text-blue-50",
    textEmphasis: "text-blue-500",
    fill: "fill-blue-500",
    fillOpacity: "fill-blue-500/50",
    fillEmphasis: "fill-blue-500",
    fillHover: "hover:fill-blue-500",
    bg: "bg-blue-500",
    bgOpacity: "bg-blue-500/50",
    bgEmphasis: "bg-blue-500",
    bgHover: "hover:bg-blue-500",
    shadow: "shadow-blue-500",
    border: "border-blue-500",
    scrollbarThumb: "scrollbar-thumb-blue-600",
    scrollbarTrack: "scrollbar-track-blue-400",
    scrollbarCorner: "scrollbar-corner-blue-400",
  },
  primary: {
    text: "text-neutral-300",
    textOpacity: "text-neutral-300/50",
    textHover: "hover:text-neutral-100",
    textEmphasis: "text-neutral-100",
    fill: "fill-neutral-300",
    fillOpacity: "fill-neutral-300/50",
    fillEmphasis: "fill-neutral-100",
    fillHover: "hover:fill-neutral-100",
    bg: "bg-neutral-950",
    bgOpacity: "bg-neutral-950/50",
    bgEmphasis: "bg-neutral-700",
    bgHover: "hover:bg-neutral-700",
    shadow: "shadow-neutral-950",
    border: "border-neutral-700",
    scrollbarThumb: "scrollbar-thumb-neutral-700",
    scrollbarTrack: "scrollbar-track-neutral-950",
    scrollbarCorner: "scrollbar-corner-neutral-950",
  },
  secondary: {
    text: "text-neutral-300",
    textOpacity: "text-neutral-300/50",
    textHover: "hover:text-neutral-100",
    textEmphasis: "text-neutral-100",
    fill: "fill-neutral-300",
    fillOpacity: "fill-neutral-300/50",
    fillEmphasis: "fill-neutral-100",
    fillHover: "hover:fill-neutral-100",
    bg: "bg-neutral-700",
    bgOpacity: "bg-neutral-700/50",
    bgEmphasis: "bg-neutral-500",
    bgHover: "hover:bg-neutral-500",
    shadow: "shadow-neutral-700",
    border: "border-neutral-500",
    scrollbarThumb: "scrollbar-thumb-neutral-500",
    scrollbarTrack: "scrollbar-track-neutral-700",
    scrollbarCorner: "scrollbar-corner-neutral-700",
  },
  white: {
    text: "text-neutral-950",
    textOpacity: "text-neutral-950/50",
    textHover: "hover:text-neutral-950",
    textEmphasis: "text-neutral-950",
    fill: "fill-neutral-950",
    fillOpacity: "fill-neutral-950/50",
    fillEmphasis: "fill-neutral-950",
    fillHover: "hover:fill-neutral-950",
    bg: "bg-neutral-950",
    bgOpacity: "bg-neutral-950/50",
    bgEmphasis: "bg-neutral-950",
    bgHover: "hover:bg-neutral-950",
    shadow: "shadow-neutral-950",
    border: "border-neutral-950",
    scrollbarThumb: "scrollbar-thumb-neutral-950",
    scrollbarTrack: "scrollbar-track-neutral-950",
    scrollbarCorner: "scrollbar-corner-neutral-950",
  },
};
