name: Test

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch: # By adding this event, you can run this workflow manually on GUI

jobs:
  run_unit_test:
    runs-on: ubuntu-latest

    permissions:
      contents: read # Required to checkout the code
      pull-requests: write # Required to put a comment into the pull-request

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run vitest Tests
        run: npm run vitest:coverage

      - name: "Report Coverage"
        if: always() # Also generate the report if tests are failing
        uses: davelosert/vitest-coverage-report-action@v2
